"""
api.py — GuardianAI · FastAPI Fraud Detection Service
======================================================
Hackathon : Fibank Real-Time Fraud Detection (GuardianAI)
Author    : ML Engineering Team

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Endpoints
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  POST /predict   → score a transaction, returns ALLOW / MFA_CHALLENGE / BLOCK
  GET  /health    → liveness probe for load-balancers / CI checks
  GET  /docs      → Swagger UI (auto-generated by FastAPI)
  GET  /redoc     → ReDoc UI

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Running the server
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # Development (auto-reload on file save):
  uvicorn api:app --reload --port 8000

  # Production / Docker:
  uvicorn api:app --host 0.0.0.0 --port 8000 --workers 2

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Integration note for Member 1 (Backend Lead)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Send a POST to http://localhost:8000/predict with Content-Type: application/json.
The request body must match the TransactionRequest schema below.
The response will always be a PredictionResponse JSON object.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Environment variables
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  GUARDIAN_MODEL_PATH   path to model.joblib  (default: "model.joblib")
  GUARDIAN_LOG_LEVEL    logging verbosity      (default: "INFO")
"""

import logging
import os
import time
from contextlib import asynccontextmanager
from typing import Literal, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from scoring_engine import ScoringEngine

# ── Logging ───────────────────────────────────────────────────────────────────
log_level = os.getenv("GUARDIAN_LOG_LEVEL", "INFO").upper()
logging.basicConfig(level=log_level, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ── Model path (override via env var for Docker / deployment) ─────────────────
MODEL_PATH = os.getenv("GUARDIAN_MODEL_PATH", "model.joblib")


# ─────────────────────────────────────────────────────────────────────────────
# PYDANTIC REQUEST SCHEMA
# ─────────────────────────────────────────────────────────────────────────────
# Field names match EXACTLY the columns in fraud_synthetic_dataset.csv,
# minus transaction_id, user_id (identifiers), and is_fraud_label (target).
#
# This class is the CONTRACT between the backend team (Member 1) and the ML
# service.  Any change here must be mirrored in scoring_engine.py and train.py.
# ─────────────────────────────────────────────────────────────────────────────
class TransactionRequest(BaseModel):
    """
    Input payload for the /predict endpoint.

    All field names come directly from fraud_synthetic_dataset.csv.
    Default values let the frontend omit optional context without errors.

    GDPR note: no personal data (name, IBAN, e-mail) is accepted here.
    Only anonymised behavioural signals are processed by the model.
    """

    transaction_amount: float = Field(
        ...,                        # required — no default
        ge=0,
        description="Transaction value in BGN.  Must be ≥ 0.",
        examples=[250.00],
    )
    hour_of_day: int = Field(
        ...,                        # required
        ge=0,
        le=23,
        description="Hour of day (0–23) when the transaction was initiated.",
        examples=[14],
    )
    is_new_device: int = Field(
        default=0,
        ge=0,
        le=1,
        description="1 if this device fingerprint was never seen for this user, else 0.",
        examples=[0],
    )
    is_new_ip: int = Field(
        default=0,
        ge=0,
        le=1,
        description="1 if this IP address was never seen for this user, else 0.",
        examples=[0],
    )
    is_foreign_country: int = Field(
        default=0,
        ge=0,
        le=1,
        description="1 if the transaction originates from outside the user's home country.",
        examples=[0],
    )
    distance_from_usual_km: float = Field(
        default=0.0,
        ge=0,
        description="Kilometres between this transaction's location and the user's typical location.",
        examples=[12.5],
    )
    is_phishing_detected: int = Field(
        default=0,
        ge=0,
        le=1,
        description=(
            "1 if a URL in the current session matched the phishing/smishing blocklist.  "
            "Triggers an immediate BLOCK via the Rule-Based Engine."
        ),
        examples=[0],
    )
    detected_url: Optional[str] = Field(
        default=None,
        description=(
            "Raw URL extracted from the current session (e.g. from a clicked link).  "
            "Scanned by the heuristic phishing engine for banking-lookalike domains "
            "and known URL shorteners.  No PII — URL only."
        ),
        examples=["https://fibank-verify.ru/secure-login"],
    )
    sms_payload: Optional[str] = Field(
        default=None,
        description=(
            "Raw SMS text forwarded by the mobile app for smishing analysis.  "
            "Scanned for high-urgency Albanian and banking-scam keywords.  "
            "Content is never stored — only a binary threat signal is produced."
        ),
        examples=["Ju lutem verifikoni llogarinë tuaj në Fibank urgjentisht."],
    )

    model_config = {
        # Reject unknown fields — prevents the backend from silently sending
        # extra data that the model ignores (a common integration bug).
        "extra": "forbid",

        # Example shown in /docs Swagger UI — useful for the demo.
        "json_schema_extra": {
            "examples": [
                {
                    "summary": "Normal transaction",
                    "value": {
                        "transaction_amount": 85.50,
                        "hour_of_day": 14,
                        "is_new_device": 0,
                        "is_new_ip": 0,
                        "is_foreign_country": 0,
                        "distance_from_usual_km": 5.2,
                        "is_phishing_detected": 0,
                    },
                },
                {
                    "summary": "Suspicious transaction (phishing + foreign + new device)",
                    "value": {
                        "transaction_amount": 1800.00,
                        "hour_of_day": 2,
                        "is_new_device": 1,
                        "is_new_ip": 1,
                        "is_foreign_country": 1,
                        "distance_from_usual_km": 9500.0,
                        "is_phishing_detected": 1,
                    },
                },
            ]
        },
    }


# ─────────────────────────────────────────────────────────────────────────────
# PYDANTIC RESPONSE SCHEMA
# ─────────────────────────────────────────────────────────────────────────────
class PredictionResponse(BaseModel):
    """
    Response from the /predict endpoint.

    Fields
    ------
    action       : The decision — what the frontend/backend should do next.
    reason       : Plain-English explanation (GDPR Article 22 compliance).
    score        : Raw Isolation Forest anomaly score.
                   Negative = more anomalous, positive = more normal.
                   0.0 when the decision was made by a hard rule (no ML needed).
    latency_ms   : Server-side inference time in milliseconds.
    """
    action:     Literal["ALLOW", "MFA_CHALLENGE", "BLOCK"]
    reason:     str
    score:      float
    latency_ms: float


# ─────────────────────────────────────────────────────────────────────────────
# APPLICATION LIFESPAN — load model once at startup, not per-request
# ─────────────────────────────────────────────────────────────────────────────
_engine: ScoringEngine | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Load the ScoringEngine once when the server boots.
    Using lifespan (not deprecated @app.on_event) is the FastAPI 0.95+ pattern.
    """
    global _engine
    log.info("GuardianAI API starting up …")
    try:
        _engine = ScoringEngine(MODEL_PATH)
        log.info("✓ ScoringEngine loaded and ready.")
    except FileNotFoundError:
        log.critical(
            f"Model file not found: '{MODEL_PATH}'.  "
            "Run `python train.py` first, then restart the API."
        )
        raise   # prevent the server from starting in a broken state
    yield
    log.info("GuardianAI API shutting down.")


# ─────────────────────────────────────────────────────────────────────────────
# FASTAPI APP
# ─────────────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="GuardianAI — Fibank Fraud Detection API",
    description=(
        "Real-time fraud detection for Fibank.\n\n"
        "Detects **Smishing/Phishing**, **Credential Theft**, and "
        "**Transaction Anomalies** using a hybrid Rule-Based + Isolation Forest approach.\n\n"
        "Every decision includes a `reason` field for GDPR Article 22 compliance."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Allow the Fibank React/Angular frontend to call this API from the browser.
# Restrict `allow_origins` to specific domains before going to production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # ← tighten to ["https://fibank.bg"] in prod
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINTS
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health", tags=["ops"], summary="Liveness probe")
def health():
    """
    Returns 200 OK when the scoring engine is loaded.
    Returns 503 if the model has not been initialised yet.
    Use this as the health check URL in Docker / Kubernetes.
    """
    if _engine is None:
        raise HTTPException(status_code=503, detail="Scoring engine not loaded.")
    return {"status": "ok", "model_loaded": True}


@app.post(
    "/predict",
    response_model=PredictionResponse,
    tags=["fraud-detection"],
    summary="Score a transaction event",
    response_description=(
        "Returns ALLOW, MFA_CHALLENGE, or BLOCK with a GDPR-compliant reason string."
    ),
)
def predict(request: TransactionRequest) -> PredictionResponse:
    """
    **Main endpoint** — receives a transaction payload and returns a fraud decision.

    ### Decision logic (in priority order):

    1. **Rule-Based Engine** — deterministic hard rules evaluated first.
       - Rule 1: `is_phishing_detected == 1`  →  **BLOCK** (Smishing protection)

    2. **Isolation Forest** — statistical anomaly scoring.
       - `predict() == -1` (anomaly)  →  **MFA_CHALLENGE**
       - `predict() == +1` (normal)   →  **ALLOW**

    ### GDPR compliance:
    - No personal identifiers are accepted or stored.
    - The `reason` field provides a specific, human-readable justification.
    - All requests are logged (no PII) for the audit trail.

    ### Integration (Member 1 / Backend):
    ```
    POST /predict
    Content-Type: application/json

    {
      "transaction_amount": 250.00,
      "hour_of_day": 14,
      "is_new_device": 0,
      "is_new_ip": 0,
      "is_foreign_country": 0,
      "distance_from_usual_km": 5.2,
      "is_phishing_detected": 0
    }
    ```
    """
    if _engine is None:
        raise HTTPException(status_code=503, detail="Scoring engine not available.")

    # ── Convert Pydantic model → plain dict for the scoring engine ────────────
    tx_dict = request.model_dump()

    t0 = time.perf_counter()

    try:
        result = _engine.evaluate_transaction(tx_dict)
    except Exception as exc:
        # Log full stack trace server-side; return a clean 500 to the caller.
        log.exception("Unexpected error in ScoringEngine.evaluate_transaction()")
        raise HTTPException(status_code=500, detail=f"Scoring failed: {exc}") from exc

    latency_ms = (time.perf_counter() - t0) * 1_000

    # ── Audit log — no PII, just the decision and key signals ─────────────────
    log.info(
        "AUDIT | action=%-14s | score=%+.4f | latency=%.1fms | "
        "amount=%.2f | hour=%d | new_device=%d | new_ip=%d | foreign=%d | phishing=%d",
        result["action"],
        result.get("score", 0.0),
        latency_ms,
        tx_dict["transaction_amount"],
        tx_dict["hour_of_day"],
        tx_dict["is_new_device"],
        tx_dict["is_new_ip"],
        tx_dict["is_foreign_country"],
        tx_dict["is_phishing_detected"],
    )

    return PredictionResponse(
        action     = result["action"],
        reason     = result["reason"],
        score      = round(result.get("score", 0.0), 6),
        latency_ms = round(latency_ms, 3),
    )


# ─────────────────────────────────────────────────────────────────────────────
# DEVELOPMENT ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("fraud_api:app", host="0.0.0.0", port=8000, reload=True)
