"""
train.py — GuardianAI Fraud Detection · Model Training
=======================================================
Hackathon : Fibank Real-Time Fraud Detection (GuardianAI)
Dataset   : fraud_synthetic_dataset.csv  (generated by Data Team)
Author    : ML Engineering Team

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Supervised RandomForestClassifier
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This script trains a RandomForestClassifier using the is_fraud_label
ground-truth column. The model learns to distinguish fraud from
legitimate transactions from labelled examples.

Usage
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    python train.py
    python train.py --data fraud_synthetic_dataset.csv --output model.joblib
"""

import argparse
import logging
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# COLUMN DEFINITIONS
# ─────────────────────────────────────────────────────────────────────────────
DROP_COLS = ["transaction_id", "user_id"]
LABEL_COL = "is_fraud_label"

FEATURE_COLS = [
    "transaction_amount",
    "hour_of_day",
    "is_new_device",
    "is_new_ip",
    "is_foreign_country",
    "distance_from_usual_km",
    "is_phishing_detected",
]


# ─────────────────────────────────────────────────────────────────────────────
# 1.  LOAD DATA
# ─────────────────────────────────────────────────────────────────────────────
def load_data(csv_path: str) -> pd.DataFrame:
    log.info(f"Loading dataset: {csv_path}")
    df = pd.read_csv(csv_path)
    log.info(f"  Shape : {df.shape[0]:,} rows × {df.shape[1]} columns")

    required = set(FEATURE_COLS) | {LABEL_COL}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(
            f"CSV is missing required columns: {missing}\n"
            "  ➜ Check the Data Team's latest export."
        )

    fraud_rate = df[LABEL_COL].mean()
    log.info(f"  Fraud rate in dataset: {fraud_rate:.2%}  "
             f"({df[LABEL_COL].sum()} fraud / {len(df)} total)")

    return df


# ─────────────────────────────────────────────────────────────────────────────
# 2.  PREPARE FEATURES
# ─────────────────────────────────────────────────────────────────────────────
def prepare_features(df: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    X = df[FEATURE_COLS].fillna(0).values.astype(np.float64)
    y = df[LABEL_COL].values.astype(int)   # 1 = fraud, 0 = normal
    return X, y


# ─────────────────────────────────────────────────────────────────────────────
# 3.  BUILD PIPELINE
# ─────────────────────────────────────────────────────────────────────────────
def build_pipeline() -> Pipeline:
    """
    Two-step sklearn Pipeline:

    ┌─ Step 1: StandardScaler ───────────────────────────────────────────────┐
    │  Centres each feature to μ=0 and σ=1.                                  │
    └────────────────────────────────────────────────────────────────────────┘
    ┌─ Step 2: RandomForestClassifier ───────────────────────────────────────┐
    │  Supervised classifier — learns from is_fraud_label ground truth.      │
    │  predict_proba() returns fraud probability in [0.0, 1.0].              │
    └────────────────────────────────────────────────────────────────────────┘
    """
    return Pipeline([
        ("scaler", StandardScaler()),
        ("clf", RandomForestClassifier(
            n_estimators=100,
            random_state=42,
            n_jobs=-1,
        )),
    ])


# ─────────────────────────────────────────────────────────────────────────────
# 4.  EVALUATE MODEL
# ─────────────────────────────────────────────────────────────────────────────
def evaluate(pipeline: Pipeline, X: np.ndarray, y_true: np.ndarray) -> None:
    y_pred = pipeline.predict(X)

    log.info("")
    log.info("━━━━  MODEL EVALUATION  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    log.info("")

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    log.info("  Confusion Matrix (rows=actual, cols=predicted):")
    log.info("                  Pred: Normal  Pred: Fraud")
    log.info(f"  Actual: Normal     {cm[0][0]:6d}        {cm[0][1]:6d}")
    log.info(f"  Actual: Fraud      {cm[1][0]:6d}        {cm[1][1]:6d}")
    log.info("")

    report = classification_report(
        y_true, y_pred,
        labels=[0, 1],
        target_names=["Normal (0)", "Fraud (1)"],
        zero_division=0,
    )
    log.info("  Classification Report:")
    for line in report.splitlines():
        log.info(f"    {line}")

    tp = cm[1][1]
    fn = cm[1][0]
    fp = cm[0][1]
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    log.info(f"  Fraud Recall    : {recall:.1%}  (of all real fraud, this % was caught)")
    log.info(f"  Fraud Precision : {precision:.1%}  (of all BLOCK decisions, this % was real fraud)")
    log.info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    log.info("")


# ─────────────────────────────────────────────────────────────────────────────
# 5.  SAVE MODEL
# ─────────────────────────────────────────────────────────────────────────────
def save_model(pipeline: Pipeline, output_path: str) -> None:
    artefact = {
        "pipeline":     pipeline,
        "feature_cols": FEATURE_COLS,
        "model_type":   "random_forest",
    }
    joblib.dump(artefact, output_path, compress=3)
    log.info(f"✓ Model saved → {output_path}")


# ─────────────────────────────────────────────────────────────────────────────
# 6.  MAIN
# ─────────────────────────────────────────────────────────────────────────────
def main(csv_path: str, output_path: str) -> None:
    df        = load_data(csv_path)
    X, y      = prepare_features(df)
    pipeline  = build_pipeline()

    log.info(f"Training RandomForestClassifier on {X.shape[0]:,} samples × {X.shape[1]} features …")
    pipeline.fit(X, y)   # ← supervised: y labels are used here
    log.info("  Training complete ✓")

    evaluate(pipeline, X, y)
    save_model(pipeline, output_path)
    log.info("All done.  Start the API with: uvicorn api:app --reload --port 8000")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train GuardianAI RandomForestClassifier")
    parser.add_argument(
        "--data",
        default="fraud_synthetic_dataset.csv",
        help="Path to the training CSV",
    )
    parser.add_argument(
        "--output",
        default="model.joblib",
        help="Destination path for the model artefact",
    )
    args = parser.parse_args()
    main(args.data, args.output)
