"""
train.py — GuardianAI Fraud Detection · Model Training
=======================================================
Hackathon : Fibank Real-Time Fraud Detection (GuardianAI)
Dataset   : fraud_synthetic_dataset.csv  (generated by Data Team)
Author    : ML Engineering Team

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GDPR / Right-to-Explanation (Article 22 GDPR)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This script trains an Isolation Forest — an *unsupervised* anomaly-
detection algorithm.  It never sees a fraud label during training; it
learns only what "normal" looks like and flags statistical deviations.

Every feature used is documented below.  No raw personal data (name,
IBAN, e-mail) enters the model — only anonymised behavioural signals.
An auditor or data-subject can request a full feature trace from the
transaction audit log.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
How Isolation Forest works  (pitch-friendly)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The algorithm builds many random decision trees.  A *normal* transaction
sits deep in the crowd and needs many splits to isolate.  An *anomalous*
transaction is a statistical outlier — it gets isolated in very few
splits.  The anomaly score is inversely proportional to the average path
length across all trees.

  score → -1  (or predict == -1)  →  anomaly  →  MFA / BLOCK
  score → +1  (or predict == +1)  →  normal   →  ALLOW

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Usage
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    python train.py
    python train.py --data fraud_synthetic_dataset.csv --output model.joblib
    python train.py --contamination 0.08   # raise if more fraud slips through
"""

import argparse
import logging
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# COLUMN DEFINITIONS  (sourced directly from fraud_synthetic_dataset.csv)
# ─────────────────────────────────────────────────────────────────────────────

# Columns that carry no predictive signal — identifiers only.
# Dropping them prevents the model from memorising user/transaction IDs.
DROP_COLS = ["transaction_id", "user_id"]

# Ground-truth label used ONLY for post-training evaluation (never for fitting).
# Keeping it separate enforces the unsupervised contract of Isolation Forest.
LABEL_COL = "is_fraud_label"

# ── Feature columns the model trains and scores on ────────────────────────────
# These MUST be identical in train.py, scoring_engine.py, and api.py.
#
# Feature          | Type  | Description
# ──────────────────|───────|─────────────────────────────────────────────────
# transaction_amount| float | Amount in BGN — unusually high amounts are risky
# hour_of_day       | int   | 0-23 — late-night / early-morning tx flag
# is_new_device     | 0/1   | 1 = device fingerprint never seen for this user
# is_new_ip         | 0/1   | 1 = IP address never seen for this user
# is_foreign_country| 0/1   | 1 = transaction originates from abroad
# distance_from_usual_km | float | km from user's typical transaction location
# is_phishing_detected   | 0/1   | 1 = session URL matched phishing blocklist
FEATURE_COLS = [
    "transaction_amount",
    "hour_of_day",
    "is_new_device",
    "is_new_ip",
    "is_foreign_country",
    "distance_from_usual_km",
    "is_phishing_detected",
]

# ─────────────────────────────────────────────────────────────────────────────
# HYPER-PARAMETERS
# ─────────────────────────────────────────────────────────────────────────────

# contamination — fraction of training rows we *expect* to be anomalous.
# The synthetic dataset has roughly 5-10 % fraud rows; start at 0.07.
# ► Too low  → model misses real fraud (false negatives).
# ► Too high → model over-blocks legitimate transactions (false positives).
# Override at runtime via --contamination flag.
DEFAULT_CONTAMINATION = 0.07


# ─────────────────────────────────────────────────────────────────────────────
# 1.  LOAD DATA
# ─────────────────────────────────────────────────────────────────────────────
def load_data(csv_path: str) -> pd.DataFrame:
    """
    Read the CSV and validate that every expected column is present.
    Raises a clear, actionable error during hackathon debugging.
    """
    log.info(f"Loading dataset: {csv_path}")
    df = pd.read_csv(csv_path)
    log.info(f"  Shape : {df.shape[0]:,} rows × {df.shape[1]} columns")

    required = set(FEATURE_COLS) | {LABEL_COL}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(
            f"CSV is missing required columns: {missing}\n"
            "  ➜ Check the Data Team's latest export."
        )

    # Report class balance — useful for choosing the contamination value.
    fraud_rate = df[LABEL_COL].mean()
    log.info(f"  Fraud rate in dataset: {fraud_rate:.2%}  "
             f"({df[LABEL_COL].sum()} fraud / {len(df)} total)")

    return df


# ─────────────────────────────────────────────────────────────────────────────
# 2.  PREPARE FEATURES
# ─────────────────────────────────────────────────────────────────────────────
def prepare_features(df: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    """
    Extract the feature matrix X and label vector y.

    X is used for unsupervised training.
    y is kept aside for evaluation only — the model never trains on it.

    GDPR note: all values are numerical; no raw PII is present.
    """
    # Fill any accidental NaN values with 0 (safe default for binary flags).
    X = df[FEATURE_COLS].fillna(0).values.astype(np.float64)

    # Isolation Forest wants +1 = normal, -1 = anomaly.
    # Our label column uses 1 = fraud, 0 = normal — invert it.
    y_true = np.where(df[LABEL_COL].values == 1, -1, 1)

    return X, y_true


# ─────────────────────────────────────────────────────────────────────────────
# 3.  BUILD PIPELINE
# ─────────────────────────────────────────────────────────────────────────────
def build_pipeline(contamination: float) -> Pipeline:
    """
    Two-step sklearn Pipeline:

    ┌─ Step 1: StandardScaler ──────────────────────────────────────────────┐
    │  Centres each feature to μ=0 and σ=1.                                 │
    │  Without this, transaction_amount (0–10 000) would overshadow binary  │
    │  flags like is_new_device (0 or 1) in the tree-split decisions.       │
    └───────────────────────────────────────────────────────────────────────┘
    ┌─ Step 2: IsolationForest ──────────────────────────────────────────────┐
    │  Unsupervised anomaly detector — no labels required.                   │
    │  contamination tells the model what fraction of data to treat as        │
    │  anomalous when setting its internal decision threshold.               │
    └───────────────────────────────────────────────────────────────────────┘

    Packaging both steps ensures the EXACT same scaling is applied at
    inference time — a common source of bugs in ML deployments.
    """
    return Pipeline([
        ("scaler", StandardScaler()),
        ("iforest", IsolationForest(
            n_estimators=200,        # 200 trees → stable, reproducible scores
            contamination=contamination,
            max_samples="auto",      # uses min(256, n_samples); fast for demos
            random_state=42,         # fixed seed → reproducible pitches
            n_jobs=-1,               # use all CPU cores
        )),
    ])


# ─────────────────────────────────────────────────────────────────────────────
# 4.  EVALUATE MODEL  (uses is_fraud_label)
# ─────────────────────────────────────────────────────────────────────────────
def evaluate(pipeline: Pipeline, X: np.ndarray, y_true: np.ndarray) -> None:
    """
    Use the held-out fraud labels to measure how well the unsupervised model
    aligns with ground truth.  This is for hackathon demo confidence — the
    model is NOT re-tuned here (that would be leakage).

    Output legend:
        -1 = predicted anomaly  (maps to MFA_CHALLENGE in production)
        +1 = predicted normal   (maps to ALLOW in production)
    """
    y_pred = pipeline.predict(X)   # returns -1 (anomaly) or +1 (normal)

    log.info("")
    log.info("━━━━  MODEL EVALUATION  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    log.info("  (using is_fraud_label as ground truth — unseen during training)")
    log.info("")

    # ── Confusion Matrix ──────────────────────────────────────────────────────
    # Rows = actual class, Columns = predicted class.
    # Labels order: [+1 normal, -1 anomaly]
    cm = confusion_matrix(y_true, y_pred, labels=[1, -1])
    log.info("  Confusion Matrix (rows=actual, cols=predicted):")
    log.info("                  Pred: Normal  Pred: Anomaly")
    log.info(f"  Actual: Normal     {cm[0][0]:6d}        {cm[0][1]:6d}")
    log.info(f"  Actual: Fraud      {cm[1][0]:6d}        {cm[1][1]:6d}")
    log.info("")

    # ── Precision / Recall / F1 ───────────────────────────────────────────────
    # Here -1 (anomaly) is our "positive" class — the fraud we want to catch.
    report = classification_report(
        y_true, y_pred,
        labels=[1, -1],
        target_names=["Normal (+1)", "Fraud/Anomaly (-1)"],
        zero_division=0,
    )
    log.info("  Classification Report:")
    for line in report.splitlines():
        log.info(f"    {line}")

    # ── Quick summary for pitch ───────────────────────────────────────────────
    tp = cm[1][1]   # fraud correctly flagged
    fn = cm[1][0]   # fraud missed
    fp = cm[0][1]   # legit transaction incorrectly blocked
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    log.info(f"  Fraud Recall    : {recall:.1%}  (of all real fraud, this % was caught)")
    log.info(f"  Fraud Precision : {precision:.1%}  (of all BLOCK decisions, this % was real fraud)")
    log.info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    log.info("")


# ─────────────────────────────────────────────────────────────────────────────
# 5.  SAVE MODEL
# ─────────────────────────────────────────────────────────────────────────────
def save_model(pipeline: Pipeline, output_path: str, contamination: float) -> None:
    """
    Persist the fitted pipeline to disk.

    We save a dict (not just the pipeline) so scoring_engine.py can verify
    at load-time that the feature list hasn't drifted since training.
    """
    artefact = {
        "pipeline":      pipeline,       # StandardScaler + IsolationForest
        "feature_cols":  FEATURE_COLS,   # ordered list — scoring engine uses this
        "contamination": contamination,  # stored for audit / reproducibility
    }
    joblib.dump(artefact, output_path, compress=3)
    log.info(f"✓ Model saved → {output_path}")


# ─────────────────────────────────────────────────────────────────────────────
# 6.  MAIN
# ─────────────────────────────────────────────────────────────────────────────
def main(csv_path: str, output_path: str, contamination: float) -> None:
    """End-to-end training run."""
    df             = load_data(csv_path)
    X, y_true      = prepare_features(df)
    pipeline       = build_pipeline(contamination)

    log.info(f"Training on {X.shape[0]:,} samples × {X.shape[1]} features …")
    pipeline.fit(X)    # ← unsupervised: y_true is NOT passed here
    log.info("  Training complete ✓")

    evaluate(pipeline, X, y_true)
    save_model(pipeline, output_path, contamination)
    log.info("All done.  Start the API with: uvicorn api:app --reload --port 8000")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train GuardianAI Isolation Forest")
    parser.add_argument(
        "--data",
        default="fraud_synthetic_dataset.csv",
        help="Path to the training CSV",
    )
    parser.add_argument(
        "--output",
        default="model.joblib",
        help="Destination path for the model artefact",
    )
    parser.add_argument(
        "--contamination",
        type=float,
        default=DEFAULT_CONTAMINATION,
        help="Expected anomaly fraction (0.01–0.5).  Tune for demo quality.",
    )
    args = parser.parse_args()
    main(args.data, args.output, args.contamination)
